  version: '3.9'

  services:
    postgres:
        container_name: postgres_db_agro
        restart: unless-stopped
        image: postgres:14
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
        volumes:
          - db_agro:/var/lib/postgresql/data
        env_file:
          - .env
        ports:
          - "5432:5432"
        networks:
          - backend

    agro_app:
      container_name: agro_app
      restart: unless-stopped
      build: .
      ports:
        - 5000:5000
      depends_on:
        - postgres
      env_file:
        - .env

  volumes:
      db_agro:
          driver: local
  networks:
      backend:
          driver: bridge
