  version: "3.9"
  services:
    postgres:
        container_name: postgres_db_agro
        restart: unless-stopped
        image: postgres:14
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
        volumes:
          - db_agro:/var/lib/postgresql/data
        env_file:
          - .env
        ports:
          - '5432:5432'
        networks:
          - backend

    app:
      container_name: agro_app
      restart: unless-stopped
      build: .
      ports:
        - '5000:5000'
      depends_on:
        - postgres
      env_file:
        - .env
      networks:
        - backend

    pgadmin:
      container_name: pgadmin_container_app
      image: dpage/pgadmin4
      depends_on:
        - postgres
      ports:
        - '127.0.0.1:5050:80'
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-tvm91@icloud.com}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-1234}
        PGADMIN_CONFIG_SERVER_MODE: 'True'
      volumes:
        - pgadmin:/var/lib/pgadmin
      restart: unless-stopped
      networks:
        - backend
      tty: true

    nginx:
      build: ./.nginx
      ports:
        - '1080:80'
      networks:
        -  backend
      depends_on:
        - app
        - pgadmin

  volumes:
      db_agro:
          driver: local
      pgadmin:
          driver: local
  networks:
      backend:
          driver: bridge
