version: '3.9'

services:
  agro_web:
    container_name: agro_web_container
    build:
    ports:
      - 5000:5000
    restart: unless-stopped

  postgres:
    env_file: ./docker/.env-postgresql
    container_name: postgresql_agro_container
    image: postgres:15
    volumes:
      - agrodb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
    - backend

    pgadmin:
      container_name: pgadmin_container
      image: dpage/pgadmin4
      enviroment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-qlik@ivan-shamaev.ru}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-A->V9>pS6HJ~xY8d}
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      volumes:
         - pgadmin:/var/lib/pgadmin
      ports:
        - "${PGADMIN_PORT:-5050}:80"
      restart: unless-stopped
      networks:
        - backend
  volumes:
      agrodb:
        driver: local
      pgadmin:
        driver: local
  networks:
    backend:
      driver: bridge