version: '3.9'
services:
  postgres:
      container_name: db_agro
      restart: unless-stopped
      image: postgres:14
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      volumes:
        - ./postgres-data/postgres:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - backend
  app:
    container_name: agro_app
    restart: unless-stopped
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    entrypoint: ["python", "start.py","runserver"]
