  version: '3.9'

  services:
    postgres:
        container_name: postgres_db_agro
        restart: unless-stopped
        image: postgres:14
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
        volumes:
          - ./postgres-data/postgres:/var/lib/postgresql/data
        ports:
          - "5432:5432"
        networks:
          - backend

    agro_app:
      container_name: agro_app
      restart: unless-stopped
      build: .
      ports:
        - 5000:5000
      volumes:
        - .:/app
      entrypoint: ["python", "start.py","runserver"]

    nginx:
      container_name: agro_server
      restart: unless-stopped
      volumes:
        -


    pgadmin:
      container_name: pgadmin_container
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-tvm91@icloud.com}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-1234}
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      volumes:
        - pgadmin:/var/lib/pgadmin
      ports:
        - "${PGADMIN_PORT:-5050}:80"
      restart: unless-stopped
      networks:
        - backend

  volumes:
      db_agro:
          driver: local
  networks:
      backend:
          driver: bridge
